version: "3.9"

services:
  tiny_url:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - zookeeper
      - mongodb
    environment:
      - BASE_URL=http://localhost:8000/url/
      - REDIS_URL=redis://redis:6379/0
      - ZOOKEEPER_HOSTS=zookeeper:2181
      - ZOOKEEPER_PATH=/tinyurls/chunk0
      - MONGO_URL=mongodb://root:example@mongodb:27017
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=tiny_url
    command: sh -c "python service/app/infrastructure/zookeeper_init.py && uvicorn service:deploy_local_app --port 8000 --host 0.0.0.0"
  redis:
    image: redis:6.2-alpine

  zookeeper:
    image: zookeeper:3.6.3


  mongodb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_DATABASE: tiny_url
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
